export enum IamExceptionSubcategories {
  MISSING_PROPERTY = 'MISSING_PROPERTY',
  INVALID_INTEGER = 'INVALID_INTEGER',
  INVALID_STRING = 'INVALID_INTEGER',
  INVALID_BOOLEAN = 'INVALID_INTEGER',
  OBJECT_ALREADY_EXISTS = 'OBJECT_ALREADY_EXISTS',
  OBJECT_NOT_FOUND = 'OBJECT_NOT_FOUND',
  LIMIT = 'LIMIT',
  EMPTY_REQUEST_BODY = 'EMPTY_REQUEST_BODY',
  INVALID_UUID = 'INVALID_UUID',
  REPEATED_ELEMENT = 'REPEATED_ELEMENT',
}
